# Generated by Django 5.0.3 on 2024-04-10 17:40

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.models import CreateModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('TypeofFood', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ItemWeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ClassofFood', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('OID', models.AutoField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=50)),
                ('StreetNumber', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=2)),
                ('Age', models.IntegerField()),
                ('AnnualIncome', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('PetID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('streetnumber', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('typeofpet', models.CharField(max_length=50)),
                ('liked_foods', models.ManyToManyField(related_name='liked_by', to='exercises.food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('PetAgeatOwnership', models.IntegerField()),
                ('PricePaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.owner')),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.food')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.owner')),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.pet')),
            ],
        ),
        migrations.RunPython(
            code=forwards_func,
            reverse_code=migrations.RunPython.noop,  # No need to reverse this
        ),
    ]
def forwards_func(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    if not schema_editor.connection.schema_editor.table_exists("django_content_type", db_alias):
        CreateModel(
            name="ContentType",
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('app_label', 'model')},
                'index_together': {('app_label', 'model')},
            },
        )(apps, schema_editor)