# Generated by Django 5.0.3 on 2024-04-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('TypeofFood', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ItemWeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ClassofFood', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('OID', models.AutoField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=50)),
                ('StreetNumber', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=2)),
                ('Age', models.IntegerField()),
                ('AnnualIncome', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(db_column='foodid', on_delete=django.db.models.deletion.CASCADE, to='exercises.food')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('PetID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('StreetNumber', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=2)),
                ('typeofpet', models.CharField(max_length=50)),
                ('liked_foods', models.ManyToManyField(related_name='liked_by_pets', through='exercises.Likes', to='exercises.food')),
                ('owner', models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='exercises.owner')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('PetAgeatOwnership', models.IntegerField()),
                ('PricePaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OID', models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='exercises.owner')),
                ('PetID', models.ForeignKey(db_column='petid', on_delete=django.db.models.deletion.CASCADE, to='exercises.pet')),
            ],
            options={
                'db_table': 'owns',
            },
        ),
        migrations.AddField(
            model_name='likes',
            name='pet',
            field=models.ForeignKey(db_column='petid', on_delete=django.db.models.deletion.CASCADE, to='exercises.pet'),
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('FoodID', models.ForeignKey(db_column='foodid', on_delete=django.db.models.deletion.CASCADE, to='exercises.food')),
                ('OID', models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='exercises.owner')),
                ('PetID', models.ForeignKey(db_column='petid', on_delete=django.db.models.deletion.CASCADE, to='exercises.pet')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
    ]
