# Generated by Django 5.0.3 on 2024-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('StreetNumber', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('ZipCode', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=2)),
                ('TypeOfPet', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
