# Generated by Django 5.0.3 on 2024-05-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
    ]
