# Generated by Django 5.0.3 on 2024-03-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='StreetNumber',
            new_name='streetnumber',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='TypeOfPet',
            new_name='typeOfPet',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='ZipCode',
            new_name='zipcode',
        ),
    ]
