# Generated by Django 5.0.3 on 2024-03-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_rename_age_pet_age_rename_city_pet_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='typeOfPet',
            new_name='typeofpet',
        ),
    ]
